name: DaySnap Home Page
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    if: "!contains(github.event.head_commit.message, '[skip vd ci]') && !contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.DAYSNAP_TOKEN }}
          TARGET_REPO: daysnap/daysnap-cli
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: npm install && npm run build
          BUILD_DIR: docs/.vuepress/dist
